language: node_js
sudo: required
dist: trusty
node_js: stable
cache: yarn
branches:
  except:
  - "/^v\\d/"
install:
- npm install -g firebase-tools
- npm install -g polymer-cli
- yarn install
- yarn global add bower
- bower install
script:
- polymer build
# after_success:
# - firebase deploy --token $FIREBASE_TOKEN --non-interactive
deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: WccIreRnzxRAOc6SMwo26h9zAGrsJcPei7TRfSUTh55p5Kxe8sGG1I5jDuue4TBqnE63OiGrBeJdDD7OGJWUgOnNjBiZo5JIWsXGeKN/4XGLufQU7NA3dg9UAQSjMtJQi7Nya/BXDnruE7FwxoflS0Kk2Vv9f0kwSgHx6QvFb7G4ZBhp6sDakXX74FQb6MIhPQNuDQ+4qawyTyir6bugBCcMYJJjSMwWxaLNw/o/BRN2ncflNpY6pL/kZnJduuEjIuwtRcL+kgTVr0HS9g8MRqbGE4bGR/Wz8YvRacQjAjNibcdf92DoYC8h+essIlCazoHOXtWKnRPQy4LA7MzTza/eRpSOrq5N75SXZjVN2d2AP2Eu32jR3RO3MY2Ua0nCX9rNrd6NWIgdJ9YlSSzrWxM7ZvKxXj2yd7tZfhyKJUxzeI6NHJPZTjsCndmCoB81m2hpjAXfGmgjz0DzEmzeK/wRaySG490tErRAOBVLQWw8pSLjPLj3EJmW+rEB+IYDgHAdqfjc25VbB/3beSFqcrB7Bul/GLF5HfiKqN3mrOCpeU3Tb9oTiAup0PVkQrTCjVFLcJboAPdk6+6D3WY+7ZxUxZcHRNkABww9B9OzUmAyBp/KOzTgd8PdTF4ZCvCdP5BFtT2vR2qWdWz20se6sSR3sthrUf4SJ0jtn5HMJo8=
    project: polymer-web
