language: node_js
sudo: required
dist: trusty
node_js: stable
cache: yarn
branches:
  except:
  - "/^v\\d/"
install:
- npm install -g firebase-tools
- npm install -g polymer-cli
- yarn install
- yarn global add bower
- bower install
script:
- polymer build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
